{{- with .Values.postgresql }}
{{- if and $.Values.stack.running .enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-200"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: phrasea
      tier: postgresql
  template:
    metadata:
      labels:
        app: phrasea
        tier: postgresql
    spec:
      volumes:
      - name: data
      {{- if .persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ .persistence.existingClaim | default (printf "%s-postgresql" (include "ps.fullname" $)) }}
      {{- else }}
        emptyDir: {}
      {{- end }}
      containers:
      - name: postgresql
        image: postgres:14.4-alpine
        {{- if eq "true" (include "ps.resourceQuota" (dict "local" .resourceQuota "global" $.Values.resourceQuota)) }}
        resources:
          requests:
            memory: {{ .resources.requests.memory | default "256Mi" }}
            cpu: {{ .resources.requests.cpu | default "100m" }}
          limits:
            memory: {{ .resources.limits.memory | default "1Gi" }}
            cpu: {{ .resources.limits.cpu | default "1000m" }}
        {{- end }}
        terminationMessagePolicy: FallbackToLogsOnError
        volumeMounts:
        - name: data
          mountPath: "/var/lib/postgresql/data"
        {{- if .persistence.enabled }}
        {{- if .persistence.subPath }}
          subPath: {{ .persistence.subPath }}
        {{- end }}
        {{- end }}
        envFrom:
        - secretRef:
            name: {{ include "secretName.postgresql" $ }}
        readinessProbe:
          exec:
            command:
              - sh
              - -c
              - |
                pg_isready -U $POSTGRES_USER -h 127.0.0.1 -p 5432
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 2
          failureThreshold: 3
          successThreshold: 1
{{- end }}
{{- end }}
