{{- with .Values.postgresql }}
{{- if not .externalSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
stringData:
  POSTGRES_USER: {{ .user | quote }}
  POSTGRES_PASSWORD: {{ .password | quote }}
  {{- if .persistence.enabled }}
  {{- if .persistence.subPath }}
  PGDATA: "/var/lib/postgresql/data/{{ .persistence.subPath }}"
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}
