{{- if and $.Values.stack.running .Values.soketi.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: soketi
  labels:
    app: phrasea
    tier: soketi
spec:
  type: ClusterIP
  ports:
    - port: 6001
      targetPort: 6001
      protocol: TCP
      name: soketi
  selector:
    app: phrasea
    tier: soketi
{{- end }}
