{{- if and $.Values.stack.running $.Values.soketi.enabled $.Values.soketi.ingress.enabled }}
apiVersion: {{ template "ingress.apiVersion" $ }}
kind: Ingress
metadata:
  name: soketi
  labels:
    app: phrasea
    tier: soketi
  {{- with $.Values.soketi.ingress.extraLabels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $.Values.soketi.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: nginx
  rules:
    - host: {{ tpl $.Values.soketi.host $ | quote }}
      http:
        paths:
        {{- include "ingress.rule_path" (dict "_" $ "name" "soketi" "port" 80) | indent 8 }}
{{- if $.Values.soketi.ingress.tls }}
  tls:
{{ toYaml $.Values.soketi.ingress.tls | indent 2 }}
{{- else if $.Values.ingress.tls.wildcard.enabled }}
  tls:
    - hosts:
        - {{ tpl $.Values.soketi.host $ | quote }}
      secretName: {{ include "secretRef.ingress.tls.wildcard" $ }}
{{- end }}
{{- end }}
