{{- if .Values.acme.enabled }}
{{- with .Values.acme }}
{{- if eq .provider "gandi" }}
{{- if and .gandi.personalAccessToken (not .gandi.existingSecretName) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "ps.fullname" $ }}-gandi-credentials
  namespace: cert-manager
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-450"
  labels:
    app: phrasea
    component: cert-manager
    provider: gandi
    release: {{ $.Release.Name }}
    api-version: livedns-v5
type: Opaque
stringData:
  api-token: {{ required "Missing acme.gandi.personalAccessToken" .gandi.personalAccessToken | quote }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
