{{- if .Values.acme.enabled }}
{{- with .Values.acme }}
{{- if eq .provider "route53" }}
{{- if and .route53.accessKeyId .route53.secretAccessKey (not .route53.existingSecretName) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "ps.fullname" $ }}-route53-credentials
  namespace: cert-manager
  labels:
    app: phrasea
    component: cert-manager
    provider: route53
    release: {{ $.Release.Name }}
type: Opaque
stringData:
  access-key-id: {{ required "Missing acme.route53.accessKeyId" .route53.accessKeyId | quote }}
  secret-access-key: {{ required "Missing acme.route53.secretAccessKey" .route53.secretAccessKey | quote }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
