{{- if .Values.acme.enabled }}
{{- with .Values.acme }}
{{- if eq .provider "scaleway" }}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ template "ps.fullname" $ }}-letsencrypt
  labels:
    app: phrasea
    component: cert-manager
    provider: scaleway
spec:
  acme:
    email: {{ required "Missing acme.email" .email | quote }}
    server: {{ ternary "https://acme-v02.api.letsencrypt.org/directory" "https://acme-staging-v02.api.letsencrypt.org/directory" .production | quote }}
    privateKeySecretRef:
      name: {{ template "ps.fullname" $ }}-acme-account-key
    solvers:
      # Scaleway DNS-01 solver using cert-manager webhook
      - dns01:
          webhook:
            groupName: acme.scaleway.com
            solverName: scaleway
            config:
              accessKeySecretRef:
                name: {{ .scaleway.existingSecretName | default (printf "%s-scaleway-credentials" (include "ps.fullname" $)) }}
                key: {{ .scaleway.existingSecretAccessKeyKey | default "SCW_ACCESS_KEY" }}
              secretKeySecretRef:
                name: {{ .scaleway.existingSecretName | default (printf "%s-scaleway-credentials" (include "ps.fullname" $)) }}
                key: {{ .scaleway.existingSecretSecretKeyKey | default "SCW_SECRET_KEY" }}
        selector:
          dnsZones:
            - {{ required "Missing acme.rootHost" .rootHost | quote }}
{{- end }}
{{- end }}
{{- end }}
