{{- with .Values.report }}
{{- if and $.Values.stack.running .enabled }}
apiVersion: v1
kind: Service
metadata:
  name: report-api
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: phrasea
    tier: report-api
{{- end }}
{{- end }}
