{{- with .Values.report }}
{{- if and $.Values.stack.running .enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: report-api
spec:
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      app: phrasea
      tier: report-api
  template:
    metadata:
      labels:
        app: phrasea
        tier: report-api
    spec:
      {{ include "imagePullSecrets" $ | indent 6 }}
      {{- if $.Values.nodeSelector }}
      nodeSelector: {{ toYaml $.Values.nodeSelector | nindent 8 }}
      {{- end }}
      containers:
      - name: report-api
        image: {{ $.Values.repository.baseurl }}/ps-report-api:{{ $.Values.repository.tag }}
        imagePullPolicy: {{ $.Values.repository.imagePullPolicy }}
        {{- if eq "true" (include "ps.resourceQuota" (dict "local" .api.resourceQuota "global" $.Values.resourceQuota)) }}
        resources:
          requests:
            memory: {{ .api.resources.requests.memory | default "256Mi" }}
            cpu: {{ .api.resources.requests.cpu | default "50m" }}
          limits:
            memory: {{ .api.resources.limits.memory | default "2048Mi" }}
            cpu: {{ .api.resources.limits.cpu | default "2000m" }}
        {{- end }}
        terminationMessagePolicy: FallbackToLogsOnError
        envFrom:
        - configMapRef:
            name: report-config
        - secretRef:
            name: {{ include "secretName.postgresql" $ }}
{{- end }}
{{- end }}
