{{- range .Values._internal.services }}
{{- $appName := . }}
{{- if and $.Values.stack.running (index $.Values $appName).enabled }}
{{- with (index $.Values $appName)  }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $appName }}-api-nginx
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: phrasea
    tier: {{ $appName }}-api-nginx
---
{{- end }}
{{- end }}
{{- end }}
