{{- range .Values._internal.services }}
{{- $appName := . }}
{{- if and $.Values.stack.running (index $.Values $appName).enabled }}
{{- with (index $.Values $appName)  }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $appName }}-api-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phrasea
      tier: {{ $appName }}-api-nginx
  template:
    metadata:
      labels:
        app: phrasea
        tier: {{ $appName }}-api-nginx
    spec:
      {{ include "imagePullSecrets" $ | indent 6 }}
      {{- if $.Values.nodeSelector }}
      nodeSelector: {{ toYaml $.Values.nodeSelector | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ $appName }}-api-nginx
        image: {{ $.Values.repository.baseurl }}/ps-{{ $appName }}-api-nginx:{{ $.Values.repository.tag }}
        imagePullPolicy: {{ $.Values.repository.imagePullPolicy }}
        terminationMessagePolicy: FallbackToLogsOnError
        env:
      {{- if .api.subnet }}
          - name: PS_SUBNET
            value: {{ .api.subnet | quote }}
      {{- end }}
      {{- if .api.ingress }}
      {{- if .api.ingress.maxBodySize }}
          - name: UPLOAD_MAX_FILE_SIZE
            value: {{ .api.ingress.maxBodySize | quote }}
      {{- end }}
      {{- end }}
---
{{- end }}
{{- end }}
{{- end }}
