{{- range .Values._internal.services }}
{{- $appName := . }}
{{- if and $.Values.stack.running (index $.Values $appName).enabled }}
{{- with (index $.Values $appName) }}
{{ $tplArgs := dict "app" $appName "ctx" . "glob" $ }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $appName }}-api-php
spec:
  replicas: {{(index $.Values $appName).api.replicas}}
  selector:
    matchLabels:
      app: phrasea
      tier: {{ $appName }}-api-php
  template:
    metadata:
      labels:
        app: phrasea
        tier: {{ $appName }}-api-php
    spec:
      {{ include "imagePullSecrets" $ | indent 6 }}
      {{- if $.Values.nodeSelector }}
      nodeSelector: {{ toYaml $.Values.nodeSelector | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ $appName }}-api-php
        image: {{ $.Values.repository.baseUrl }}/ps-{{ $appName }}-api-php:{{ $.Values.repository.tag }}
        imagePullPolicy: {{ $.Values.repository.imagePullPolicy }}
        {{- if eq "true" (include "ps.resourceQuota" (dict "local" (index $.Values $appName).api.resourceQuota "global" $.Values.resourceQuota)) }}
        resources:
          requests:
            memory: {{ (index $.Values $appName).api.resources.requests.memory | default "256Mi" }}
            cpu: {{ (index $.Values $appName).api.resources.requests.cpu | default "50m" }}
          limits:
            memory: {{ (index $.Values $appName).api.resources.limits.memory | default "2048Mi" }}
            cpu: {{ (index $.Values $appName).api.resources.limits.cpu | default "2000m" }}
        {{- end }}
        readinessProbe:
          tcpSocket:
            port: 9000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 2
          failureThreshold: 3
          successThreshold: 1
        terminationMessagePolicy: FallbackToLogsOnError
        env:
        {{- include "envRef.phpApp" $tplArgs | indent 8 }}
        {{- include "envRef.configuratorSecrets" $ | indent 8 }}
        {{- if .api.ingress }}
        {{- if .api.ingress.maxBodySize }}
        - name: UPLOAD_MAX_FILE_SIZE
          value: {{ .api.ingress.maxBodySize | quote }}
        {{- end }}
        {{- end }}
        envFrom:
        {{- include "envFrom.phpApp" $ | indent 8 }}
        {{- include "envFrom.rabbitmq" $ | indent 8 }}
        {{- include "envFrom.postgresql" $ | indent 8 }}
        - secretRef:
            name: {{ .adminOAuthClient.externalSecretName | default (printf "%s-admin-oauth-client-secret" $appName) }}
        {{- if (eq "databox" $appName) }}
        - secretRef:
            name: {{ $appName }}-secrets
        - configMapRef:
            name: imagemagick-policies
        {{- end }}
        - configMapRef:
            name: {{ $appName }}-api-config
        {{- if $.Values.soketi.enabled }}
        - configMapRef:
            name: soketi
        - secretRef:
            name: soketi
        {{- end }}
        {{- if $.Values.matomo }}
        {{- if $.Values.matomo.enabled }}
        - configMapRef:
            name: matomo
        - secretRef:
            name: matomo
        {{- end }}
        {{- end }}
---
{{- end }}
{{- end }}
{{- end }}
