{{- range .Values._internal.services }}
{{- $appName := . }}
{{- if and $.Values.stack.running (index $.Values $appName).enabled }}
{{- with (index $.Values $appName).api  }}
{{- $apiNode := . }}
{{- if .ingress }}
{{- if .ingress.enabled }}
apiVersion: {{ template "ingress.apiVersion" $ }}
kind: Ingress
metadata:
  name: {{ $appName }}-api-ingress
{{- if .ingress.annotations }}
  annotations:
{{ toYaml .ingress.annotations | indent 4 }}
{{- end }}
{{- if .ingress.extraLabels }}
  labels:
{{ toYaml .ingress.extraLabels | indent 4 }}
{{- end }}
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .hostname }}
    http:
      paths:
      {{- include "ingress.rule_path" (dict "_" $ "name" (printf "%s-api-nginx" $appName) "port" 80) | indent 6 }}
{{- if .ingress.tls }}
{{- $tlsNode := .ingress.tls -}}
{{- range $value := $tlsNode }}
  {{- if not (hasKey $value "hosts") }}
    {{- $hosts := list $apiNode.hostname }}
    {{- $_ := set $value "hosts" $hosts }}
  {{- end -}}
{{- end }}
  tls:
{{ toYaml $tlsNode | indent 2 }}
{{- else if $.Values.ingress.tls.wildcard.enabled }}
  tls:
  - hosts:
    - {{ .hostname }}
    secretName: {{ include "secretRef.ingress.tls.wildcard" $ }}
{{- end }}
---
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
