apiVersion: v1
kind: ConfigMap
metadata:
  name: client-config
data:
  NOTIFICATIONS_ENABLED: {{ .Values.notifications.enabled | quote }}
  # Used to fetch the stack configuration from the configurator bucket
  VERIFY_SSL: {{ .Values.security.verifySsl | quote }}
