apiVersion: v1
kind: ConfigMap
metadata:
  name: php-config
data:
  APP_ENV: prod
  VERIFY_SSL: {{ .Values.security.verifySsl | default true | quote }}
  TRUSTED_PROXIES: {{ .Values.security.trustedProxies | default '127.0.0.1,REMOTE_ADDR' | quote }}
  NOTIFICATIONS_ENABLED: {{ .Values.notifications.enabled | default false | quote }}
{{- if .Values.newrelic.enabled }}
  NEWRELIC_ENABLED: "1"
  NEWRELIC_LICENSE_KEY: {{ required "Missing newrelic.licenceKey" .Values.newrelic.licenceKey | quote }}
{{- end }}
{{- $sentry := .Values.sentry | default dict }}
{{- $sentryBackend := get $sentry "backend" | default dict }}
{{- $sentryBackendEnabled := get $sentryBackend "enabled" }}
{{- if eq $sentryBackendEnabled nil }}
{{- $sentryBackendEnabled = (get $sentry "enabled" | default false) }}
{{- end }}
{{- $sentryBackendDsn := get $sentryBackend "dsn" }}
{{- if eq $sentryBackendDsn nil }}
{{- $sentryBackendDsn = (get $sentry "dsn") }}
{{- end }}
{{- if $sentryBackendEnabled }}
  SENTRY_DSN: {{ required "Missing sentry backend DSN (sentry.backend.dsn or sentry.dsn)" $sentryBackendDsn | quote }}
  SENTRY_ENVIRONMENT: {{ required "Missing sentry environment (sentry.environment)" (get $sentry "environment") | quote }}
{{- end }}
