{{- with .Values.soketi }}
{{- if .enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: soketi
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-20"
data:
  SOKETI_HOST: {{ required "Missing soketi.host" .host | quote }}
  SOKETI_APP_ID: {{ required "Missing soketi.appId" .appId | quote }}
  SOKETI_KEY: {{ required "Missing soketi.key" .key | quote }}
---
{{- end }}
{{- end }}
