apiVersion: v1
kind: ConfigMap
metadata:
  name: urls-config
data:
  STACK_NAME: {{ .Values.stack.name | default "" | quote }}
  STACK_VERSION: {{ .Values.repository.tag | quote }}
  REPORT_API_URL: {{ required "Missing report.api.baseUrl" .Values.report.api.baseUrl | quote }}
  KEYCLOAK_URL: {{ required "Missing keycloak.baseUrl" .Values.keycloak.baseUrl | quote }}
  KEYCLOAK_REALM_NAME: {{ required "Missing mailer.dsn value" .Values.keycloak.realm.name | quote }}
  EXPOSE_API_URL: {{ required "Missing expose.api.baseUrl" .Values.expose.api.baseUrl | quote }}
  EXPOSE_CLIENT_URL: {{ required "Missing expose.client.baseUrl" .Values.expose.client.baseUrl | quote }}
  DATABOX_API_URL: {{ required "Missing databox.api.baseUrl" .Values.databox.api.baseUrl | quote }}
  DATABOX_CLIENT_URL: {{ required "Missing databox.client.baseUrl" .Values.databox.client.baseUrl | quote }}
  UPLOADER_API_URL: {{ required "Missing uploader.api.baseUrl" .Values.uploader.api.baseUrl | quote }}
  UPLOADER_CLIENT_URL: {{ required "Missing uploader.client.baseUrl" .Values.uploader.client.baseUrl | quote }}
  DASHBOARD_URL: {{ required "Missing dashboard.baseUrl" .Values.dashboard.baseUrl | quote }}
  DASHBOARD_CLIENT_URL: {{ required "Missing dashboard.baseUrl" .Values.dashboard.baseUrl | quote }}
  DISPLAY_SERVICES_MENU: {{ ternary "true" "false" .Values.dashboard.menuEnabled | quote }}
