{{- with .Values.keycloak }}
{{- if and $.Values.stack.running .enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phrasea
      tier: keycloak
  template:
    metadata:
      labels:
        app: phrasea
        tier: keycloak
    spec:
      {{ include "imagePullSecrets" $ | indent 6 }}
      {{- if $.Values.nodeSelector }}
      nodeSelector: {{ toYaml $.Values.nodeSelector | nindent 8 }}
      {{- end }}
      containers:
        - name: keycloak
          image: {{ $.Values.repository.baseUrl }}/ps-keycloak:{{ $.Values.repository.tag }}
          args:
          - 'start'
          - '--optimized'
          imagePullPolicy: {{ $.Values.repository.imagePullPolicy }}
          {{- if eq "true" (include "ps.resourceQuota" (dict "local" .resourceQuota "global" $.Values.resourceQuota)) }}
          resources:
            requests:
              memory: {{ .resources.requests.memory }}
              cpu: {{ .resources.requests.cpu }}
            limits:
              memory: {{ .resources.limits.memory }}
              cpu: {{ .resources.limits.cpu }}
          {{- end }}
          terminationMessagePolicy: FallbackToLogsOnError
          ports:
            - name: http
              containerPort: 8080
            - name: management
              containerPort: 9000
          startupProbe:
            httpGet:
              path: /health/started
              port: management
            periodSeconds: 5
            failureThreshold: 60
          readinessProbe:
            httpGet:
              path: /health/ready
              port: management
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health/live
              port: management
            periodSeconds: 30
            failureThreshold: 3
          envFrom:
            - secretRef:
                name: {{ include "secretName.postgresql" $ }}
            - secretRef:
                name: keycloak
            - configMapRef:
                name: urls-config
            - configMapRef:
                name: mailer
            - secretRef:
                name: {{ include "secretName.mailer" $ }}
          env:
          - name: KC_HTTP_ENABLED
            value: 'true'
          - name: KC_PROXY_HEADERS
            value: xforwarded
          {{- with .proxyTrustedAddresses }}
          - name: KC_PROXY_TRUSTED_ADDRESSES
            value: {{ . | quote }}
          {{- end }}
          - name: KC_HOSTNAME
            value: {{ tpl .baseUrl $ | quote }}
          - name: KC_DB
            value: postgres
          - name: KC_LOGIN_CSS_BACKGROUND
            value: {{ .realm.loginCssBackground | quote }}
          - name: KC_LOGIN_CSS_LOGO_BACKGROUND
            value: {{ .realm.loginCssLogoBackground | quote }}
          - name: KC_LOGIN_DISPLAY_DASHBOARD_LINK
            value: {{ .realm.loginDisplayDashboardLink | quote }}
{{- end }}
{{- end }}
