{{- with .Values.keycloak }}
apiVersion: v1
kind: Secret
metadata:
  name: keycloak
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-20"
    "helm.sh/resource-policy": "keep"
stringData:
{{- with .masterAdmin }}
  KEYCLOAK_ADMIN: {{ .username | quote }}
  KEYCLOAK_ADMIN_PASSWORD: {{ .password | quote }}
{{- end }}
{{- with .defaultAdmin }}
  DEFAULT_ADMIN_USERNAME: {{ .username | quote }}
  DEFAULT_ADMIN_PASSWORD: {{ .password | quote }}
{{- end }}
{{- with $.Values.postgresql }}
  KC_DB_USERNAME: {{ .user | quote }}
  KC_DB_PASSWORD: {{ .password | quote }}
  KC_DB_URL: jdbc:postgresql://{{ .host }}:{{ .port }}/{{ $.Values.keycloak.database.name }}
{{- end }}
{{- end }}
