{{- with .Values.configurator.s3 }}
{{- if not .externalSecretKey  }}
apiVersion: v1
kind: Secret
metadata:
  name: configurator-s3
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-20"
    "helm.sh/resource-policy": "keep"
stringData:
  CONFIGURATOR_S3_ACCESS_KEY: {{ .accessKey | default (ternary $.Values.minio.accessKey "" $.Values.minio.enabled) | quote }}
  CONFIGURATOR_S3_SECRET_KEY: {{ .secretKey | default (ternary $.Values.minio.secretKey "" $.Values.minio.enabled) | quote }}
{{- end }}
{{- end }}
