{{- with .Values.mailer }}
apiVersion: v1
kind: Secret
metadata:
  name: mailer
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-10"
    "helm.sh/resource-policy": "keep"
stringData:
  MAILER_USER: {{ .user | quote }}
  MAILER_PASSWORD: {{ .password | quote }}
---
{{- end }}