{{- with .Values.mailer }}
apiVersion: v1
kind: Secret
metadata:
  name: mailer
stringData:
  MAILER_USER: {{ .user | default "" | quote }}
  MAILER_PASSWORD: {{ .password | default "" | quote }}
  MAILER_DSN: {{ tpl (.dsn| default "") $ | quote }}
---
{{- end }}
