{{- with .Values.mailer }}
{{- if not .externalSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: mailer
stringData:
  MAILER_USER: {{ .user | default "" | quote }}
  MAILER_PASSWORD: {{ .password | default "" | quote }}
{{- end }}
{{- end }}
