{{- with .Values.soketi }}
{{- if .enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: soketi
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-470"
stringData:
  SOKETI_SECRET: {{ required "Missing soketi.secret" .secret | quote }}
---
{{- end }}
{{- end }}
