{{- if and $.Values.stack.running $.Values.soketi.enabled }}
{{- with .Values.soketi }}
apiVersion: v1
kind: Secret
metadata:
  name: soketi
stringData:
  SOKETI_SECRET: {{ required "Missing soketi.secret" .secret | quote }}
---
{{- end }}
{{- end }}
