stack:
  domain: "local"
  tlsEnabled: false

zippy:
  ingress:
    baseUrl: "https://zippy.local"
    hostname: "zippy.local"

soketi:
  key: "soketi-key"
  secret: "soketi-secret"


novu:
  secretKey: "novu-secret"
  applicationIdentifier: "novu-app-id"

databox:
  api:
    config:
      secrets:
        publicKey: "databox-public-key"
        secretKey: "databox-secret-key"

elasticsearch:
  imageTag: 7.17.28

repository:
  tag: configurator-fixes
  baseUrl: public.ecr.aws/b2s9z7l1

security:
  verifySsl: false
