{{- with .Values.uploader }}
{{- if .enabled }}
{{- $tplArgs := dict "ctx" . "glob" $ }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: uploader-client-config
data:
  ALLOWED_FILE_TYPES: {{ $.Values.uploader.allowedFileTypes | quote }}
  S3_MAX_OBJECT_SIZE: {{ .s3MaxObjectSize | default "52776558133248" | quote }}
  {{- include "app.client.configMap" $tplArgs | indent 2 }}
{{- end }}
{{- end }}
