{{- if and $.Values.stack.running .Values.uploader.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uploader-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phrasea
      tier: uploader-client
  template:
    metadata:
      labels:
        app: phrasea
        tier: uploader-client
    spec:
      {{ include "imagePullSecrets" $ | indent 6 }}
      {{- if $.Values.nodeSelector }}
      nodeSelector: {{ toYaml $.Values.nodeSelector | nindent 8 }}
      {{- end }}
      containers:
      - name: uploader-client
        image: {{ $.Values.repository.baseurl }}/ps-uploader-client:{{ $.Values.repository.tag }}
        imagePullPolicy: {{ $.Values.repository.imagePullPolicy }}
        {{- if eq "true" (include "ps.resourceQuota" (dict "local" $.Values.uploader.client.resourceQuota "global" $.Values.resourceQuota)) }}
        resources:
          requests:
            memory: {{ $.Values.uploader.client.resources.requests.memory | default "64Mi" }}
            cpu: {{ $.Values.uploader.client.resources.requests.cpu | default "25m" }}
          limits:
            memory: {{ $.Values.uploader.client.resources.limits.memory | default "256Mi" }}
            cpu: {{ $.Values.uploader.client.resources.limits.cpu | default "500m" }}
        {{- end }}
        terminationMessagePolicy: FallbackToLogsOnError
        env:
        - name: DEV_MODE
          value: "false"
        envFrom:
        - configMapRef:
            name: urls-config
        - configMapRef:
            name: novu
        - configMapRef:
            name: uploader-client-config
        - configMapRef:
            name: configurator-s3
{{- end }}
