{{- if and $.Values.stack.running .Values.uploader.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uploader-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phrasea
      tier: uploader-client
  template:
    metadata:
      labels:
        app: phrasea
        tier: uploader-client
      annotations:
        {{- include "annotation.checksum.configs" $ | indent 8 }}
    spec:
      {{ include "imagePullSecrets" $ | indent 6 }}
      {{- if $.Values.nodeSelector }}
      nodeSelector: {{ toYaml $.Values.nodeSelector | nindent 8 }}
      {{- end }}
      volumes:
{{- include "volumes.configs" $ | indent 8 }}
      containers:
      - name: uploader-client
        image: {{ $.Values.repository.baseurl }}/ps-uploader-client:{{ $.Values.repository.tag }}
        imagePullPolicy: {{ $.Values.repository.imagePullPolicy }}
        terminationMessagePolicy: FallbackToLogsOnError
        volumeMounts:
        - name: configs
          mountPath: /configs
        env:
        - name: DEV_MODE
          value: "false"
        envFrom:
        - configMapRef:
            name: urls-config
        - configMapRef:
            name: novu
        - configMapRef:
            name: uploader-client-config
        - configMapRef:
            name: configurator-s3
{{- end }}
