{{- if and $.Values.stack.running $.Values.stack.runMigrations }}
{{ $appName := "configurator" }}
{{- with (index $.Values $appName)  }}
{{ $tplArgs := dict "app" $appName "ctx" . "glob" $ }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $appName }}-migrate
  annotations:
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      {{- include "imagePullSecrets" $ | indent 6 }}
      {{- if $.Values.nodeSelector }}
      nodeSelector: {{ toYaml $.Values.nodeSelector | nindent 8 }}
      {{- end }}
      containers:
      - {{- include "configurator.containerSpecs" $ | nindent 8 }}
        {{- if eq "true" (include "ps.resourceQuota" (dict "local" $.Values.configurator.resourceQuota "global" $.Values.resourceQuota)) }}
        resources:
          requests:
            memory: {{ $.Values.configurator.resources.requests.memory | default "256Mi" }}
            cpu: {{ $.Values.configurator.resources.requests.cpu | default "50m" }}
          limits:
            memory: {{ $.Values.configurator.resources.limits.memory | default "2048Mi" }}
            cpu: {{ $.Values.configurator.resources.limits.cpu | default "2000m" }}
        {{- end }}
        args: ["bin/migrate.sh"]
      restartPolicy: Never
  backoffLimit: 3
---
{{- end }}
{{- end }}
