{{- if and $.Values.stack.running $.Values.redis.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-160"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phrasea
      tier: redis
  template:
    metadata:
      labels:
        app: phrasea
        tier: redis
    spec:
      containers:
      - name: redis
        image: redis:5.0.5-alpine
        {{- if eq "true" (include "ps.resourceQuota" (dict "local" $.Values.redis.resourceQuota "global" $.Values.resourceQuota)) }}
        resources:
          requests:
            memory: {{ $.Values.redis.resources.requests.memory | default "64Mi" }}
            cpu: {{ $.Values.redis.resources.requests.cpu | default "25m" }}
          limits:
            memory: {{ $.Values.redis.resources.limits.memory | default "256Mi" }}
            cpu: {{ $.Values.redis.resources.limits.cpu | default "500m" }}
        {{- end }}
        terminationMessagePolicy: FallbackToLogsOnError
{{- end }}
