{{- if and $.Values.stack.running $.Values.redis.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phrasea
      tier: redis
  template:
    metadata:
      labels:
        app: phrasea
        tier: redis
    spec:
      containers:
      - name: redis
        image: {{ $.Values.redis.image }}
        {{- if eq "true" (include "ps.resourceQuota" (dict "local" $.Values.redis.resourceQuota "global" $.Values.resourceQuota)) }}
        resources:
          requests:
            memory: {{ $.Values.redis.resources.requests.memory }}
            cpu: {{ $.Values.redis.resources.requests.cpu }}
          limits:
            memory: {{ $.Values.redis.resources.limits.memory }}
            cpu: {{ $.Values.redis.resources.limits.cpu }}
        {{- end }}
        terminationMessagePolicy: FallbackToLogsOnError
{{- end }}
