{{- with .Values.expose }}
{{- if and $.Values.stack.running .enabled }}
{{- $tplArgs := dict "ctx" . "glob" $ }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: expose-client-config
data:
  S3_REQUEST_SIGNATURE_TTL: {{ .api.config.requestSignatureTtl | quote }}
  DISABLE_INDEX_PAGE: {{ ternary "true" "false" .client.disableIndexPage | quote }}
  {{- include "app.client.configMap" $tplArgs | indent 2 }}
{{- end }}
{{- end }}
