{{- if and $.Values.stack.running .Values.expose.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: expose-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phrasea
      tier: expose-client
  template:
    metadata:
      labels:
        app: phrasea
        tier: expose-client
    spec:
      {{ include "imagePullSecrets" $ | indent 6 }}
      {{- if $.Values.nodeSelector }}
      nodeSelector: {{ toYaml $.Values.nodeSelector | nindent 8 }}
      {{- end }}
      containers:
      - name: expose-client
        image: {{ $.Values.repository.baseurl }}/ps-expose-client:{{ $.Values.repository.tag }}
        imagePullPolicy: {{ $.Values.repository.imagePullPolicy }}
        {{- if eq "true" (include "ps.resourcesquota" (dict "local" $.Values.expose.client.resourcesquota "global" $.Values.resourcesquota)) }}
        resources:
          requests:
            memory: {{ $.Values.expose.client.resources.requests.memory | default "64Mi" }}
            cpu: {{ $.Values.expose.client.resources.requests.cpu | default "25m" }}
          limits:
            memory: {{ $.Values.expose.client.resources.limits.memory | default "256Mi" }}
            cpu: {{ $.Values.expose.client.resources.limits.cpu | default "500m" }}
        {{- end }}
        terminationMessagePolicy: FallbackToLogsOnError
        envFrom:
        - configMapRef:
            name: urls-config
        - configMapRef:
            name: novu
        - configMapRef:
            name: expose-client-config
        - configMapRef:
            name: configurator-s3
{{- end }}
