{{- if .Values.report.createDatabase }}
{{ $jobName := "postgresql-create-report-database" }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $jobName }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      containers:
      - name: {{ $jobName }}
        image: jbergknoff/postgresql-client
        command: ["sh", "-c"]
        args:
          - |
            #!/bin/sh
            set -e

            DB="{{ .Values.report.databaseName }}"

            DSN="postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@{{ .Values.postgresql.host }}:{{ .Values.postgresql.port }}"
            psql ${DSN} -tc "SELECT 1 FROM pg_database WHERE datname = '$DB'" | grep -q 1 || psql ${DSN} -c "CREATE DATABASE $DB"
        envFrom:
        - secretRef:
            name: {{ .Values.postgresql.externalSecretName | default "postgresql-secret" }}
      restartPolicy: Never
  backoffLimit: 10
{{- end }}
