{{- if and $.Values.stack.running .Values.minio.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-140"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phrasea
      tier: minio
  template:
    metadata:
      labels:
        app: phrasea
        tier: minio
    spec:
      {{- if $.Values.nodeSelector }}
      nodeSelector: {{ toYaml $.Values.nodeSelector | nindent 8 }}
      {{- end }}
      containers:
      - name: minio
        image: minio/minio
        {{- if eq "true" (include "ps.resourceQuota" (dict "local" $.Values.minio.resourceQuota "global" $.Values.resourceQuota)) }}
        resources:
          requests:
            memory: {{ $.Values.minio.resources.requests.memory | default "256Mi" }}
            cpu: {{ $.Values.minio.resources.requests.cpu | default "50m" }}
          limits:
            memory: {{ $.Values.minio.resources.limits.memory | default "1Gi" }}
            cpu: {{ $.Values.minio.resources.limits.cpu | default "1000m" }}
        {{- end }}
        terminationMessagePolicy: FallbackToLogsOnError
        args:
        - "server"
        - "/data"
        - "--console-address"
        - ":9001"
        env:
          {{- if .Values.minio.console.enabled }}
          - name: MINIO_BROWSER_REDIRECT_URL
            value: {{ printf "https://%s" (tpl .Values.minio.console.hostname $) | quote }}
          {{- end }}
        envFrom:
          - secretRef:
              name: minio-secret
        volumeMounts:
          - name: data
            mountPath: "/data"
      volumes:
        - name: data
          {{- if .Values.minio.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.minio.persistence.existingClaim | default (printf "%s-minio" (include "ps.fullname" .)) }}
          {{- else }}
          emptyDir: {}
          {{- end }}
{{- end }}
