{{- if and $.Values.stack.running .Values.minio.enabled }}
{{- if .Values.minio.console.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: minio-console
spec:
  ports:
  - name: minio-console
    port: 9001
    targetPort: 9001
  selector:
    app: phrasea
    tier: minio
{{- end }}
{{- end }}
