{{- if and .Values.minio.enabled }}
{{ $jobName := "minio-create-buckets" }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $jobName }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      {{- if $.Values.nodeSelector }}
      nodeSelector: {{ toYaml $.Values.nodeSelector | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ $jobName }}
        image: minio/mc:RELEASE.2020-09-18T00-13-21Z
        command: ["sh", "-c"]
        args:
          - |
            #!/bin/sh
            set -ex

            while ! nc -z minio 80; do
              echo "Wait for minio to startup..." && sleep 0.1;
            done;
            sleep 5
            mc config host add minio http://minio:80 $MINIO_ACCESS_KEY $MINIO_SECRET_KEY
            mc mb --ignore-existing minio/{{ .Values.expose.api.config.s3Storage.bucketName }}
            mc mb --ignore-existing minio/{{ .Values.uploader.api.config.s3Storage.bucketName }}
            mc mb --ignore-existing minio/{{ .Values.databox.api.config.s3Storage.bucketName }}
            mc mb --ignore-existing minio/{{ .Values.configurator.s3.bucketName }}
        terminationMessagePolicy: FallbackToLogsOnError
        envFrom:
        - secretRef:
            name: minio-secret
      restartPolicy: Never
  backoffLimit: 0
{{- end }}
