{{- if and $.Values.stack.running .Values.minio.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phrasea
      tier: minio
  template:
    metadata:
      labels:
        app: phrasea
        tier: minio
    spec:
      {{- if $.Values.nodeSelector }}
      nodeSelector: {{ toYaml $.Values.nodeSelector | nindent 8 }}
      {{- end }}
      containers:
      - name: minio
        image: minio/minio
        terminationMessagePolicy: FallbackToLogsOnError
        args:
        - "server"
        - "/data"
        - "--console-address"
        - ":9001"
        env:
          {{- if .Values.minio.console.enabled }}
          - name: MINIO_BROWSER_REDIRECT_URL
            value: https://{{ .Values.minio.console.hostname }}
          {{- end }}
        envFrom:
          - secretRef:
              name: minio-secret
        volumeMounts:
          - name: data
            mountPath: "/data"
      volumes:
        - name: data
          {{- if .Values.minio.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.minio.persistence.existingClaim | default (printf "%s-minio" (include "ps.fullname" .)) }}
          {{- else }}
          emptyDir: {}
          {{- end }}
{{- end }}
