{{- with .Values.novu }}
{{- if .enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: novu
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-20"
    "helm.sh/resource-policy": "keep"
stringData:
  NOVU_SECRET_KEY: {{ required "Missing novu.secretKey value" .secretKey | quote }}
---
{{- end }}
{{- end }}
