{{- with .Values.novu }}
{{- if .enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: novu
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-20"
    "helm.sh/resource-policy": "keep"
data:
  NOVU_API_HOST: {{ required "Missing novu.apiHost" .apiHost | quote }}
  NOVU_API_URL: {{ (print "https://" (required "Missing novu.apiHost" .apiHost)) | quote }}
  NOVU_DASHBOARD_URL: {{ required "Missing novu.dashboardUrl" .dashboardUrl | quote }}
  NOVU_BRIDGE_URL: {{ required "Missing novu.bridge.baseUrl" .bridge.baseUrl | quote }}
  NOVU_WS_URL: {{ required "Missing novu.wsUrl" .wsUrl | quote }}
  NOVU_APPLICATION_IDENTIFIER: {{ required "Missing novu.applicationIdentifier" .applicationIdentifier | quote }}
{{- end }}
{{- end }}
