{{- if and $.Values.stack.running .Values.novu.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: novu-bridge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phrasea
      tier: novu-bridge
  template:
    metadata:
      labels:
        app: phrasea
        tier: novu-bridge
    spec:
      {{ include "imagePullSecrets" $ | indent 6 }}
      {{- if $.Values.nodeSelector }}
      nodeSelector: {{ toYaml $.Values.nodeSelector | nindent 8 }}
      {{- end }}
      containers:
      - name: novu-bridge
        {{- if eq "true" (include "ps.resourceQuota" (dict "local" $.Values.novu.bridge.resourceQuota "global" $.Values.resourceQuota)) }}
        resources:
          requests:
            memory: {{ $.Values.novu.bridge.resources.requests.memory | default "128Mi" }}
            cpu: {{ $.Values.novu.bridge.resources.requests.cpu | default "25m" }}
          limits:
            memory: {{ $.Values.novu.bridge.resources.limits.memory | default "512Mi" }}
            cpu: {{ $.Values.novu.bridge.resources.limits.cpu | default "500m" }}
        {{- end }}
        {{- include "novuBridge.containerSpecs" $ | nindent 8 }}
{{- end }}
