{{- with .Values.rabbitmq }}
{{- if and $.Values.stack.running .enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: phrasea
      tier: rabbitmq
  template:
    metadata:
      labels:
        app: phrasea
        tier: rabbitmq
    spec:
      {{- if $.Values.nodeSelector }}
      nodeSelector: {{ toYaml $.Values.nodeSelector | nindent 8 }}
      {{- end }}
      volumes:
      - name: data
      {{- if .persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ .persistence.existingClaim | default (printf "%s-rabbitmq" (include "ps.fullname" $)) }}
      {{- else }}
        emptyDir: {}
      {{- end }}
      hostAliases:
        - ip: "127.0.0.1"
          hostnames:
            - "rabbitmq"
      containers:
      - name: rabbitmq
        image: {{ .image }}
        terminationMessagePolicy: FallbackToLogsOnError
        volumeMounts:
        - name: data
          mountPath: "/var/lib/rabbitmq"
        env:
        - name: RABBITMQ_DEFAULT_USER
          valueFrom:
            secretKeyRef:
              name: {{ include "secretName.rabbitmq" $ }}
              key: RABBITMQ_USER
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: {{ include "secretName.rabbitmq" $ }}
              key: RABBITMQ_PASSWORD
        envFrom:
        - configMapRef:
            name: rabbitmq-config
      {{- if or .securityContext.runAsUser .securityContext.runAsGroup }}
      securityContext:
        {{- if .securityContext.runAsUser }}
        runAsUser: {{ .securityContext.runAsUser }}
        {{- end }}
        {{- if .securityContext.runAsGroup }}
        runAsGroup: {{ .securityContext.runAsGroup }}
        {{- end }}
      {{- end }}
{{- end }}
{{- end }}
