{{- if .Values.expose.enabled }}
{{- with .Values.expose }}
{{- if .matomo.enabled }}
{{- with .matomo }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: matomo
data:
  MATOMO_URL: {{ .baseUrl | quote }}
  MATOMO_SITE_ID: {{ .siteId | quote }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
