{{- if .Values.matomo.enabled }}
{{- with .Values.matomo }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: matomo
data:
  MATOMO_URL: {{ .baseUrl | quote }}
  MATOMO_SITE_ID: {{ .siteId | quote }}
  MATOMO_MEDIA_PLUGIN_ENABLED: {{ .mediaPluginEnabled | default false | quote }}
{{- end }}
{{- end }}
