{{- if $.Values.matomo.enabled }}
{{- if $.Values.matomo.syncPhraseanet.enabled }}
{{- $appName := "expose" }}
{{- with $.Values.expose }}
{{- $tplArgs := dict "app" $appName "ctx" . "glob" $ }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: matomo-phraseanet-sync
spec:
  schedule: {{ $.Values.matomo.syncPhraseanet.schedule | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          {{- include "imagePullSecrets" $ | indent 10 }}
          {{- if $.Values.nodeSelector }}
          nodeSelector: {{ toYaml $.Values.nodeSelector | nindent 12 }}
          {{- end }}
          containers:
          - name: {{ $appName }}-api-php
            image: {{ $.Values.repository.baseUrl }}/ps-{{ $appName }}-api-php:{{ $.Values.repository.tag }}
            imagePullPolicy: {{ $.Values.repository.imagePullPolicy }}
            command:
              - bin/console
              - app:matomo:sync-phraseanet
            terminationMessagePolicy: FallbackToLogsOnError
            env:
            {{- include "envRef.phpApp" $tplArgs | indent 12 }}
            {{- include "envRef.configuratorSecrets" $ | indent 12 }}
            envFrom:
            {{- include "envFrom.phpApp" $ | indent 12 }}
            {{- include "envFrom.rabbitmq" $ | indent 12 }}
            {{- include "envFrom.postgresql" $ | indent 12 }}
            - secretRef:
                name: {{ .adminOAuthClient.externalSecretName | default (printf "%s-admin-oauth-client-secret" $appName) }}
            - configMapRef:
                name: {{ $appName }}-api-config
            - configMapRef:
                name: matomo
            - secretRef:
                name: matomo
          restartPolicy: OnFailure
{{- end }}
{{- end }}
{{- end }}
