{{- if .Values.matomo.enabled }}
{{- with .Values.matomo }}
apiVersion: v1
kind: Secret
metadata:
  name: matomo
stringData:
  MATOMO_AUTH_TOKEN: {{ required "Missing Values.matomo.authToken" .authToken | quote }}
{{- end }}
{{- end }}
