{{- if and $.Values.stack.running .Values.databox.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: databox-client
spec:
  ports:
  - name: http
    port: 80
    targetPort: {{ .Values.databox.client.port | default 3000 }}
  selector:
    app: phrasea
    tier: databox-client
{{- end }}
