{{- with .Values.databox.api.config.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: databox-secrets
stringData:
  SECRETS_PUBLIC_KEY: {{ required "Missing databox.api.config.secrets.publicKey value" .publicKey | quote }}
---
{{- end }}
